### ISSUE TITLE
Inquiry: Where to find the finetuned model weights and architecture? 

### ISSUE THREAD

**Issue by lamoboos223** [Nutlope/llama-ocr#5]
based on the code: https://github.com/Nutlope/llama-ocr/blob/13bc0fb2bd06171a950896ffa133dfdeef1f3e8f/src/index.ts#L1C23-L1C34

i see you're using a model inside this library but where to find the polished finetuned model that you're calling? as i'm planning to deploy it in homelab.

@Nutlope

**Comment by TKDKid1000** [comment]
There is no fine-tuned model in use here. They are solely calling the standard instruction-tuned Llama 3.2 Vision models. They're available both on Together and on Huggingface:
- [11B](https://huggingface.co/meta-llama/Llama-3.2-11B-Vision-Instruct)
- [90B](https://huggingface.co/meta-llama/Llama-3.2-90B-Vision-Instruct)

**Comment by lamoboos223** [comment]
Thanks, @TKDKid1000

**Comment by MlLearnerAkash** [comment]
Thanks for details
